/**
 * Notification Types & Rules
 * STEP 22: Notifications & Reminders Engine
 */

// ============================================
// NOTIFICATION TYPE CONSTANTS
// ============================================

// Timeline-based notifications
export const RFP_TIMELINE_QA_WINDOW_OPEN = 'RFP_TIMELINE_QA_WINDOW_OPEN';
export const RFP_TIMELINE_QA_WINDOW_CLOSING_SOON = 'RFP_TIMELINE_QA_WINDOW_CLOSING_SOON';
export const RFP_TIMELINE_SUBMISSION_WINDOW_OPEN = 'RFP_TIMELINE_SUBMISSION_WINDOW_OPEN';
export const RFP_TIMELINE_SUBMISSION_DEADLINE_SOON = 'RFP_TIMELINE_SUBMISSION_DEADLINE_SOON';
export const RFP_TIMELINE_SUBMISSION_DEADLINE_PASSED = 'RFP_TIMELINE_SUBMISSION_DEADLINE_PASSED';
export const RFP_TIMELINE_DEMO_WINDOW_OPEN = 'RFP_TIMELINE_DEMO_WINDOW_OPEN';
export const RFP_TIMELINE_AWARD_DATE_SOON = 'RFP_TIMELINE_AWARD_DATE_SOON';
export const RFP_TIMELINE_AWARD_DATE_PASSED = 'RFP_TIMELINE_AWARD_DATE_PASSED';

// Q&A and interaction notifications
export const SUPPLIER_QUESTION_CREATED = 'SUPPLIER_QUESTION_CREATED';
export const SUPPLIER_QUESTION_ANSWERED = 'SUPPLIER_QUESTION_ANSWERED';
export const SUPPLIER_BROADCAST_CREATED = 'SUPPLIER_BROADCAST_CREATED';

// Response notifications
export const SUPPLIER_RESPONSE_SUBMITTED = 'SUPPLIER_RESPONSE_SUBMITTED';
export const SUPPLIER_RESPONSE_REMINDER = 'SUPPLIER_RESPONSE_REMINDER';
export const SUPPLIER_RESPONSE_VIEWED_BY_BUYER = 'SUPPLIER_RESPONSE_VIEWED_BY_BUYER';

// Readiness and comparison notifications
export const READINESS_INDICATOR_UPDATED = 'READINESS_INDICATOR_UPDATED';
export const COMPARISON_REPORT_READY = 'COMPARISON_REPORT_READY';

// ============================================
// CATEGORY CONSTANTS
// ============================================

export const RFP_TIMELINE = 'RFP_TIMELINE';
export const SUPPLIER_QA = 'SUPPLIER_QA';
export const SUPPLIER_RESPONSE = 'SUPPLIER_RESPONSE';
export const READINESS = 'READINESS';
export const SYSTEM = 'SYSTEM';

// ============================================
// TYPESCRIPT TYPES
// ============================================

export type NotificationType =
  | typeof RFP_TIMELINE_QA_WINDOW_OPEN
  | typeof RFP_TIMELINE_QA_WINDOW_CLOSING_SOON
  | typeof RFP_TIMELINE_SUBMISSION_WINDOW_OPEN
  | typeof RFP_TIMELINE_SUBMISSION_DEADLINE_SOON
  | typeof RFP_TIMELINE_SUBMISSION_DEADLINE_PASSED
  | typeof RFP_TIMELINE_DEMO_WINDOW_OPEN
  | typeof RFP_TIMELINE_AWARD_DATE_SOON
  | typeof RFP_TIMELINE_AWARD_DATE_PASSED
  | typeof SUPPLIER_QUESTION_CREATED
  | typeof SUPPLIER_QUESTION_ANSWERED
  | typeof SUPPLIER_BROADCAST_CREATED
  | typeof SUPPLIER_RESPONSE_SUBMITTED
  | typeof SUPPLIER_RESPONSE_REMINDER
  | typeof SUPPLIER_RESPONSE_VIEWED_BY_BUYER
  | typeof READINESS_INDICATOR_UPDATED
  | typeof COMPARISON_REPORT_READY;

export type NotificationCategory =
  | typeof RFP_TIMELINE
  | typeof SUPPLIER_QA
  | typeof SUPPLIER_RESPONSE
  | typeof READINESS
  | typeof SYSTEM;

export type NotificationChannel = 'IN_APP' | 'EMAIL' | 'IN_APP_EMAIL';

// ============================================
// HELPER EXPORTS
// ============================================

export const ALL_NOTIFICATION_TYPES: NotificationType[] = [
  RFP_TIMELINE_QA_WINDOW_OPEN,
  RFP_TIMELINE_QA_WINDOW_CLOSING_SOON,
  RFP_TIMELINE_SUBMISSION_WINDOW_OPEN,
  RFP_TIMELINE_SUBMISSION_DEADLINE_SOON,
  RFP_TIMELINE_SUBMISSION_DEADLINE_PASSED,
  RFP_TIMELINE_DEMO_WINDOW_OPEN,
  RFP_TIMELINE_AWARD_DATE_SOON,
  RFP_TIMELINE_AWARD_DATE_PASSED,
  SUPPLIER_QUESTION_CREATED,
  SUPPLIER_QUESTION_ANSWERED,
  SUPPLIER_BROADCAST_CREATED,
  SUPPLIER_RESPONSE_SUBMITTED,
  SUPPLIER_RESPONSE_REMINDER,
  SUPPLIER_RESPONSE_VIEWED_BY_BUYER,
  READINESS_INDICATOR_UPDATED,
  COMPARISON_REPORT_READY,
];

export const ALL_CATEGORIES: NotificationCategory[] = [
  RFP_TIMELINE,
  SUPPLIER_QA,
  SUPPLIER_RESPONSE,
  READINESS,
  SYSTEM,
];
