/**
 * STEP 40: Executive Summary PDF Export API
 * 
 * GET /api/dashboard/rfps/[id]/executive-summaries/[summaryId]/pdf
 */

import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth-options';
import { prisma } from '@/lib/prisma';
import { logActivity } from '@/lib/activity-log';

/**
 * GET /api/dashboard/rfps/[id]/executive-summaries/[summaryId]/pdf
 * Export a summary as PDF
 */
export async function GET(
  request: NextRequest,
  { params }: { params: { id: string; summaryId: string } }
) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.id) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { id: rfpId, summaryId } = params;

    // Verify RFP access
    const rfp = await prisma.rFP.findFirst({
      where: {
        id: rfpId,
        userId: session.user.id,
      },
    });

    if (!rfp) {
      return NextResponse.json({ error: 'RFP not found' }, { status: 404 });
    }

    // Fetch summary
    const summary = await prisma.executiveSummaryDocument.findUnique({
      where: { id: summaryId },
      include: {
        author: {
          select: {
            name: true,
          },
        },
      },
    });

    if (!summary || summary.rfpId !== rfpId) {
      return NextResponse.json({ error: 'Summary not found' }, { status: 404 });
    }

    // Generate HTML for PDF
    const htmlContent = generatePDFHTML(summary, rfp);

    // Log activity
    await logActivity({
      eventType: 'EXECUTIVE_SUMMARY_EXPORTED' as any,
      actorRole: 'BUYER',
      summary: `Executive summary v${summary.version} exported as PDF`,
      userId: session.user.id,
      rfpId,
      details: {
        summaryId: summary.id,
        format: 'pdf',
      },
    });

    // Return HTML content with PDF headers
    // In a production app, you would use a library like Puppeteer or jsPDF to generate actual PDF
    return new NextResponse(htmlContent, {
      status: 200,
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': `attachment; filename="executive-summary-${rfp.title.replace(/\s+/g, '-')}.html"`,
      },
    });
  } catch (error) {
    console.error('Error exporting executive summary:', error);
    return NextResponse.json(
      { error: 'Failed to export summary' },
      { status: 500 }
    );
  }
}

function generatePDFHTML(summary: any, rfp: any): string {
  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${summary.title} - ${rfp.title}</title>
  <style>
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px 20px;
    }
    h1, h2, h3 {
      color: #1a1a1a;
    }
    h1 {
      border-bottom: 3px solid #3b82f6;
      padding-bottom: 10px;
    }
    .header {
      margin-bottom: 30px;
    }
    .metadata {
      background: #f3f4f6;
      padding: 15px;
      border-radius: 5px;
      margin-bottom: 30px;
    }
    .metadata p {
      margin: 5px 0;
    }
    .content {
      margin-top: 30px;
    }
    @media print {
      body {
        padding: 20px;
      }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>${summary.title}</h1>
  </div>
  
  <div class="metadata">
    <p><strong>RFP:</strong> ${rfp.title}</p>
    <p><strong>Version:</strong> ${summary.version}</p>
    <p><strong>Author:</strong> ${summary.author?.name || 'Unknown'}</p>
    <p><strong>Tone:</strong> ${summary.tone}</p>
    <p><strong>Audience:</strong> ${summary.audience}</p>
    <p><strong>Generated:</strong> ${summary.generatedAt ? new Date(summary.generatedAt).toLocaleDateString() : 'Manual'}</p>
    <p><strong>Last Updated:</strong> ${new Date(summary.updatedAt).toLocaleDateString()}</p>
  </div>
  
  <div class="content">
    ${summary.content}
  </div>
  
  <div style="margin-top: 50px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 0.9em; color: #666;">
    <p>Generated by Fyndr RFP Management System</p>
    <p>Date: ${new Date().toLocaleDateString()}</p>
  </div>
</body>
</html>
  `.trim();
}
